# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 14:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_auto_20150608_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='folder',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bookshelf.Tag'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bookshelf.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
