# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0013_auto_20160401_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='ebook',
            field=models.BooleanField(default=False),
        ),
    ]
